-- Procedures de Insert

-- Users

CREATE OR REPLACE PROCEDURE PRC_INS_USER(
    P_USERNAME IN VARCHAR2,
    P_EMAIL IN VARCHAR2,
    P_PASSWORD IN VARCHAR2,
    P_FULLNAME IN VARCHAR2,
    P_PHONE IN VARCHAR2,
    P_ROLE IN VARCHAR2
)
AS
BEGIN
    INSERT INTO TB_GS_USERS (USERNAME, EMAIL, PASSWORD, FULLNAME, PHONE, ROLE)
    VALUES (P_USERNAME, P_EMAIL, P_PASSWORD, P_FULLNAME, P_PHONE, P_ROLE);
END;
/


-- Sectors

CREATE OR REPLACE PROCEDURE PRC_INS_SECTOR(
    P_NAME IN VARCHAR2,
    P_DESCRIPTION IN VARCHAR2,
    P_SUPERVISOR_ID IN NUMBER
)
AS
BEGIN
    INSERT INTO TB_GS_SECTORS (NAME, DESCRIPTION, SUPERVISOR_ID)
    VALUES (P_NAME, P_DESCRIPTION, P_SUPERVISOR_ID);
END;
/



-- Sensors

CREATE OR REPLACE PROCEDURE PRC_INS_SENSOR (
    P_SECTOR_ID IN NUMBER,
    P_NAME IN VARCHAR2,
    P_TYPE IN VARCHAR2
) AS
BEGIN
    INSERT INTO TB_GS_SENSORS (SECTOR_ID, NAME, TYPE)
    VALUES (P_SECTOR_ID, P_NAME, P_TYPE);
END;
/

-- Sensors Readings

CREATE OR REPLACE PROCEDURE PRC_INS_SENSOR_READING (
    P_SENSOR_ID IN NUMBER,
    P_TEMPERATURE IN NUMBER,
    P_HUMIDITY IN NUMBER,
    P_RAINFALL IN NUMBER,
    P_LIGHT IN NUMBER,
    P_WIND_SPEED IN NUMBER,
    P_SOIL_MOISTURE IN NUMBER
) AS
BEGIN
    INSERT INTO TB_GS_SENSOR_READINGS 
    (SENSOR_ID, TEMPERATURE, HUMIDITY, RAINFALL, LIGHT, WIND_SPEED, SOIL_MOISTURE)
    VALUES 
    (P_SENSOR_ID, P_TEMPERATURE, P_HUMIDITY, P_RAINFALL, P_LIGHT, P_WIND_SPEED, P_SOIL_MOISTURE);
END;
/

-- Notifications
CREATE OR REPLACE PROCEDURE PRC_INS_NOTIFICATION (
    P_TITLE IN VARCHAR2,
    P_DESCRIPTION IN VARCHAR2,
    P_METRIC IN VARCHAR2,
    P_MEASURED_VALUE IN NUMBER,
    P_THRESHOLD_VALUE IN NUMBER,
    P_STATUS IN VARCHAR2,
    P_USER_ID IN NUMBER,
    P_SECTOR_ID IN NUMBER
)
AS
BEGIN
    INSERT INTO TB_GS_NOTIFICATIONS (
        TITLE,
        DESCRIPTION,
        METRIC,
        MEASURED_VALUE,
        THRESHOLD_VALUE,
        STATUS,
        USER_ID,
        SECTOR_ID
    )
    VALUES (
        P_TITLE,
        P_DESCRIPTION,
        P_METRIC,
        P_MEASURED_VALUE,
        P_THRESHOLD_VALUE,
        P_STATUS,
        P_USER_ID,
        P_SECTOR_ID
    );
END;
/

